# Generated by Django 5.0.6 on 2024-07-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RecommendModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "recommend_type",
                    models.CharField(
                        choices=[("music", "Music"), ("movie", "Movie")],
                        max_length=50,
                        verbose_name="推荐类型",
                    ),
                ),
                ("content", models.TextField(verbose_name="内容")),
            ],
            options={
                "verbose_name": "推荐",
                "verbose_name_plural": "推荐",
                "db_table": "recommend",
            },
        ),
    ]
