# Generated by Django 5.0.6 on 2024-08-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppOpenModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="打开时间"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="名称")),
            ],
            options={
                "verbose_name": "app打开记录",
                "verbose_name_plural": "app打开记录",
                "db_table": "app_open",
            },
        ),
        migrations.AlterField(
            model_name="recommendmodel",
            name="content",
            field=models.JSONField(verbose_name="内容"),
        ),
    ]
