# Generated by Django 5.0.6 on 2024-07-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='年')),
                ('month', models.PositiveSmallIntegerField(verbose_name='月')),
                ('day', models.PositiveSmallIntegerField(verbose_name='日')),
                ('content', models.TextField(verbose_name='日程')),
            ],
            options={
                'verbose_name': '日程',
                'verbose_name_plural': '日程',
                'db_table': 'calendar',
            },
        ),
        migrations.CreateModel(
            name='PlanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='年')),
                ('month', models.PositiveSmallIntegerField(verbose_name='月')),
                ('day', models.PositiveSmallIntegerField(verbose_name='日')),
                ('content', models.TextField(verbose_name='规划后日程')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='最后更新日期')),
            ],
            options={
                'verbose_name': '规划',
                'verbose_name_plural': '规划',
                'db_table': 'plan',
            },
        ),
    ]
